export const categories = [
  { id: "sinhala", name: "Sinhala", count: 245, icon: "si" },
  { id: "english", name: "English", count: 312, icon: "en" },
  { id: "mathematics", name: "Mathematics", count: 489, icon: "math" },
  { id: "science", name: "Science", count: 367, icon: "sci" },
  { id: "history", name: "History", count: 178, icon: "hist" },
  { id: "religion", name: "Religion", count: 134, icon: "rel" },
  { id: "basket1", name: "Basket 1", count: 256, icon: "b1" },
  { id: "basket2", name: "Basket 2", count: 198, icon: "b2" },
  { id: "basket3", name: "Basket 3", count: 145, icon: "b3" },
]

export const documents = [
  {
    id: "1",
    title: "Mathematics Chapter 5 - Algebra Fundamentals",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Kavinda Perera", avatar: "/placeholder.svg" },
    upvotes: 234,
    views: 1567,
    downloads: 892,
    category: "mathematics",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-15",
  },
  {
    id: "2",
    title: "O/L Science Past Paper 2024",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Nethmi Silva", avatar: "/placeholder.svg" },
    upvotes: 456,
    views: 2341,
    downloads: 1234,
    category: "science",
    type: "papers",
    medium: "sinhala",
    createdAt: "2025-01-14",
  },
  {
    id: "3",
    title: "English Grammar Complete Guide",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 189,
    views: 987,
    downloads: 567,
    category: "english",
    type: "books",
    medium: "english",
    createdAt: "2025-01-13",
  },
  {
    id: "4",
    title: "Sinhala Sahithya Notes - Grade 11",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Dilshan Rajapaksa", avatar: "/placeholder.svg" },
    upvotes: 312,
    views: 1890,
    downloads: 1023,
    category: "sinhala",
    type: "notes",
    medium: "sinhala",
    createdAt: "2025-01-12",
  },
  {
    id: "5",
    title: "History - Colonial Period Summary",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Sachini Weerasinghe", avatar: "/placeholder.svg" },
    upvotes: 267,
    views: 1234,
    downloads: 678,
    category: "history",
    type: "notes",
    medium: "sinhala",
    createdAt: "2025-01-11",
  },
  {
    id: "6",
    title: "Buddhism Chapter Notes - Complete",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Thisara Mendis", avatar: "/placeholder.svg" },
    upvotes: 198,
    views: 876,
    downloads: 456,
    category: "religion",
    type: "notes",
    medium: "sinhala",
    createdAt: "2025-01-10",
  },
  {
    id: "7",
    title: "ICT Practical Guide 2025",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Nuwan Bandara", avatar: "/placeholder.svg" },
    upvotes: 345,
    views: 2100,
    downloads: 1456,
    category: "basket1",
    type: "books",
    medium: "english",
    createdAt: "2025-01-09",
  },
  {
    id: "8",
    title: "Commerce Short Notes - All Chapters",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ishara Jayawardena", avatar: "/placeholder.svg" },
    upvotes: 289,
    views: 1678,
    downloads: 934,
    category: "basket2",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-08",
  },
  {
    id: "9",
    title: "Art & Crafts Model Paper Collection",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Kasun Rathnayake", avatar: "/placeholder.svg" },
    upvotes: 156,
    views: 654,
    downloads: 345,
    category: "basket3",
    type: "papers",
    medium: "sinhala",
    createdAt: "2025-01-07",
    comments: 8,
  },
  {
    id: "10",
    title: "English Comprehension - Practice Set A",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 78,
    views: 523,
    downloads: 234,
    category: "english",
    type: "papers",
    medium: "english",
    createdAt: "2025-01-06",
    comments: 12,
  },
  {
    id: "11",
    title: "English Vocabulary Builder - 500 Words",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 156,
    views: 834,
    downloads: 456,
    category: "english",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-05",
    comments: 4,
  },
  {
    id: "12",
    title: "Essay Writing Guide - Complete",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 234,
    views: 1245,
    downloads: 678,
    category: "english",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-04",
    comments: 2,
  },
  {
    id: "13",
    title: "Shakespeare - Macbeth Analysis",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 189,
    views: 987,
    downloads: 567,
    category: "english",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-03",
    comments: 18,
  },
  {
    id: "14",
    title: "English Grammar - Tenses Explained",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 267,
    views: 1456,
    downloads: 789,
    category: "english",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-02",
    comments: 3,
  },
  {
    id: "15",
    title: "Poetry Analysis - Short Poems Collection",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 145,
    views: 654,
    downloads: 345,
    category: "english",
    type: "notes",
    medium: "english",
    createdAt: "2025-01-01",
    comments: 22,
  },
  {
    id: "16",
    title: "Idioms and Phrasal Verbs - Quick Guide",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 98,
    views: 432,
    downloads: 201,
    category: "english",
    type: "notes",
    medium: "english",
    createdAt: "2024-12-31",
    comments: 5,
  },
  {
    id: "17",
    title: "English Listening Comprehension - Practice",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Ashan Fernando", avatar: "/placeholder.svg" },
    upvotes: 201,
    views: 876,
    downloads: 456,
    category: "english",
    type: "papers",
    medium: "english",
    createdAt: "2024-12-30",
    comments: 1,
  },
]

export const notifications = [
  {
    id: "1",
    type: "comment",
    message: "Kavinda left a comment: 'This was so helpful!'",
    documentTitle: "Mathematics Chapter 5",
    timestamp: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    type: "download",
    message: "Your O/L Science Past Paper was downloaded 50 times!",
    documentTitle: "O/L Science Past Paper 2024",
    timestamp: "5 hours ago",
    read: false,
  },
  {
    id: "3",
    type: "system",
    message: "Welcome to StudyShare! Start by uploading your first document.",
    timestamp: "1 day ago",
    read: true,
  },
]

export const userUploads = documents.slice(0, 4)
export const userDownloads = documents.slice(4, 8)

export const adminPendingReview = [
  {
    id: "p1",
    title: "Untitled Document",
    thumbnail: "/placeholder.svg",
    uploader: { name: "New User", avatar: "/placeholder.svg", totalUploads: 1 },
    suggestedCategory: "mathematics",
    confidence: 65,
    status: "uncertain",
  },
  {
    id: "p2",
    title: "Multiple Images Upload",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Kavinda Perera", avatar: "/placeholder.svg", totalUploads: 12 },
    suggestedCategory: "science",
    confidence: 82,
    status: "compile",
  },
  {
    id: "p3",
    title: "Possible Duplicate - Math Notes",
    thumbnail: "/placeholder.svg",
    uploader: { name: "Anonymous", avatar: "/placeholder.svg", totalUploads: 3 },
    suggestedCategory: "mathematics",
    confidence: 45,
    status: "duplicate",
  },
]

export const adminDownvoted = [
  {
    id: "d1",
    title: "Incorrect Information Document",
    downvotes: 12,
    upvotes: 2,
    ratio: 0.14,
    uploader: { name: "Unknown User", avatar: "/placeholder.svg" },
  },
  {
    id: "d2",
    title: "Low Quality Scan",
    downvotes: 8,
    upvotes: 5,
    ratio: 0.38,
    uploader: { name: "New Contributor", avatar: "/placeholder.svg" },
  },
]

export const adminUsers = [
  {
    id: "u1",
    name: "Kavinda Perera",
    email: "kavinda@example.com",
    uploads: 23,
    downloads: 156,
    commentsSent: 45,
    joinDate: "2024-06-15",
  },
  {
    id: "u2",
    name: "Nethmi Silva",
    email: "nethmi@example.com",
    uploads: 45,
    downloads: 234,
    commentsSent: 78,
    joinDate: "2024-05-20",
  },
  {
    id: "u3",
    name: "Ashan Fernando",
    email: "ashan@example.com",
    uploads: 12,
    downloads: 89,
    commentsSent: 23,
    joinDate: "2024-08-10",
  },
]
